#!bin/sh
sudo bash -c 'echo "* soft nofile 102400" >> /etc/security/limits.conf'
sudo bash -c 'echo "* hard nofile 102400" >> /etc/security/limits.conf'
sudo bash -c 'echo "fs.file-max=6553550" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.core.wmem_max=8388608" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.core.wmem_default=8388608" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.core.rmem_max=33554432" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.core.rmem_default=33554432" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.core.netdev_max_backlog=100000" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.icmp_ratelimit=0" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.tcp_tw_recycle=1" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.tcp_tw_reuse=1" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.tcp_max_tw_buckets=65536" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.tcp_fin_timeout=15" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.tcp_max_syn_backlog=65536" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.tcp_syncookies=1" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.neigh.default.gc_thresh1=4096" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.neigh.default.gc_thresh2=4096" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.neigh.default.gc_thresh3=4096" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.conf.all.rp_filter=0" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.conf.all.arp_filter=0" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.conf.default.rp_filter=0" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.conf.default.arp_filter=0" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.conf.eth0.rp_filter=0" >> /etc/sysctl.conf'
sudo bash -c 'echo "net.ipv4.conf.eth0.arp_filter=0" >> /etc/sysctl.conf'
sudo sysctl -p
cd /var/tmp
wget http://nginx.org/keys/nginx_signing.key
sudo apt-key add nginx_signing.key
sudo bash -c "echo 'deb http://nginx.org/packages/ubuntu/ trusty nginx' >> /etc/apt/sources.list"
sudo apt-get update
sudo apt-get -y install nginx redis-server
wget http://172.29.172.152/downloads/scale_image/nginx.conf
sudo mv nginx.conf /etc/nginx/nginx.conf
sudo mkdir /data
sudo mkdir /data/www
sudo chmod -R 777 /data
cd /data/www
wget http://172.29.172.152/downloads/scale_image/index.tar.gz .
tar xzf index.tar.gz
rm index.tar.gz
cd /var/tmp
wget http://172.29.172.152/downloads/scale_image/nuttcp-7.3.2
chmod +x nuttcp-7.3.2
sudo sed -i "s/127.0.0.1/0.0.0.0/g" /etc/redis/redis.conf
sudo sed -i "s/^exit\s0/\/var\/tmp\/nuttcp-7.3.2 -P5002 -S --single-threaded\n\0/g" /etc/rc.local
sudo sed -i "s/^exit\s0/cd \/var\/tmp\n\0/g" /etc/rc.local
sudo sed -i "s/^exit\s0/wget http\:\/\/169.254.169.254\/latest\/user-data\n\0/g" /etc/rc.local
sudo sed -i "s/^exit\s0/python \/var\/tmp\/kb_vm_agent.py \&\n\0/g" /etc/rc.local
sudo sed -i "s/^exit\s0/cd -\n\n\0/g" /etc/rc.local
sudo sed -i 's/start-stop-daemon\ --start/ulimit\ \-n\ 102400\n\ \ \ \ \0/g' /etc/init.d/nginx

# ======
# Client
# ======
cd /var/tmp
# sudo apt-get -y install libgo5
sudo apt-get clean
wget http://172.29.172.152/downloads/scale_image/redis-2.10.3.tar.gz
tar xzf redis-2.10.3.tar.gz
cd redis-2.10.3
sudo python setup.py install
cd -
sudo rm -rf redis-2.10.3
rm -f redis-2.10.3.tar.gz
wget http://172.29.172.152/downloads/scale_image/wrk-4.0.1
chmod +x wrk-4.0.1
wget http://172.29.172.152/downloads/scale_image/wrk2-3.1.1
chmod +x wrk2-3.1.1
# wget http://172.29.172.152/downloads/scale_image/gobench
# chmod +x gobench
wget http://172.29.172.152/downloads/scale_image/kb_vm_agent.py
wget http://172.29.172.152/downloads/scale_image/kb.lua
rm -f /var/tmp/scripts
sync
history -cw
